name: Deploy Azure Function App (api)

on:
  workflow_dispatch
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Function App from infra/api
        run: |
          cd infra/api
          zip -r ../../functionapp.zip .

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: myhugoblog-funcjwpb
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Test Function API
        run: |
          sleep 15
          curl -i -X POST https://myhugoblog-funcjwpb.azurewebsites.net/api/submit_form \
            -H "Content-Type: application/json" \
            -d '{"name":"CI Test","email":"test@example.com","message":"Deployed from GitHub Actions!"}'
